project:
  type: website
  output-dir: docs
  
website:
  title: "Luis D. Aguilar Chachagua"
  navbar:
    background: "#8eed94"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: Ernest Prete.qmd
        text: Ernest Prete Jr. Foundation
      - href: resume/Resume 2024.pdf
        text: Resume
      

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

