---
title: "Ernest Prete Jr. Foundation"
---

## Program Experience

Through my time in the internship, I found a new passion for teaching ignited within me. Spending the time in the class room, helping students understand their math work and reading along with them as they dived into stories of different topics showed me the true work that needs to be done as a teacher. Getting to spend time with the students assisting them in their school store, attending Saturday school as an assistant, and going on a field trip with the students to Medieval Times helped me create a connection with the students beyond just on an instructional level.

## Program Description

Attached find the link to the About section in the foundation's webpage.
<https://www.cpp.edu/sci/cemast/prete/about.shtml>


## Lesson Plan

Attached is the google drive containing the materials and lesson plan presented to the students of the 6th grade class.
<https://drive.google.com/drive/folders/11Sb-gTsGz5ry8yuPTnK7VF4b9cb812Vz?usp=drive_link>

## Photos

## Student Testimonials

*(You could always have a full friends list, but have an empty lobby - Jakob V.)*

*(Just because you have the best players doesn't mean you'll win everytime - Alex R.)*